name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: "УМФ_лаба1.sln"

  BUILD_CONFIGURATION: Release

  PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} ${{env.SOLUTION_FILE_PATH}}
